packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.4.2+sha512-psEBPeRC6fDGpnwSiRrYPqWi9yvHudqkbXdEIxrwbxhHBiOKiflCYZdkIs57fyzg5GRyFLXtwhZ/D4viiEm/vQ==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@savvy-web/lint-staged"
  - core-js
  - esbuild
  - msgpackr-extract
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - commitizen
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
