packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.6.3+sha512-P2oTH3CRDxvEqVtavf5adiX2B4MQGU2GA2INDBwrDHiPJLWke3Sjpqr5tgba3+gc1wyDS5YgELsWizAr94WkDQ==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@savvy-web/lint-staged"
  - core-js
  - esbuild
  - msgpackr-extract
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - commitizen
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
