/**
 * Zod schemas for commitlint configuration options.
 *
 * @internal
 */
import { z } from "zod";

/**
 * Release format schema for the release commit type.
 *
 * @remarks
 * Determines how release commits are formatted based on versioning strategy:
 * - `semver`: `release: v1.2.3` (for single/fixed-group versioning)
 * - `packages`: `release: version packages` (for independent versioning)
 * - `scoped`: `release(pkg): v1.2.3` (for per-package releases)
 *
 * @internal
 */
export const ReleaseFormatSchema = z.enum(["semver", "packages", "scoped"]);

/**
 * Release format type derived from the schema.
 *
 * @public
 */
export type ReleaseFormat = z.infer<typeof ReleaseFormatSchema>;

/**
 * Zod schema for validating {@link ConfigOptions}.
 *
 * @remarks
 * This schema validates and applies defaults to user-provided configuration.
 * Used internally by {@link CommitlintConfig.silk}.
 *
 * @internal
 */
export const ConfigOptionsSchema = z.object({
	dco: z.boolean().optional(),
	scopes: z.array(z.string()).optional(),
	additionalScopes: z.array(z.string()).optional(),
	releaseFormat: ReleaseFormatSchema.optional(),
	emojis: z.boolean().default(false),
	bodyMaxLineLength: z.number().positive().default(300),
	noMarkdown: z.boolean().default(true),
	cwd: z.string().optional(),
});

/**
 * Configuration options for {@link CommitlintConfig.silk}.
 *
 * @remarks
 * All properties are optional. When omitted, values are auto-detected
 * from the repository structure or use sensible defaults.
 *
 * @public
 */
export interface ConfigOptions {
	/**
	 * Enable DCO signoff requirement.
	 *
	 * @remarks
	 * - `true`: Always require signoff
	 * - `false`: Never require signoff
	 * - `undefined`: Auto-detect from DCO file presence
	 *
	 * @defaultValue Auto-detected
	 */
	dco?: boolean;

	/**
	 * Allowed scopes for commits.
	 *
	 * @remarks
	 * When provided, replaces auto-detected scopes entirely.
	 * For monorepos, scopes are auto-detected from workspace package names.
	 *
	 * @defaultValue Auto-detected from workspace packages
	 */
	scopes?: string[];

	/**
	 * Additional scopes to add to auto-detected scopes.
	 *
	 * @remarks
	 * Unlike `scopes`, this does not replace auto-detected values
	 * but adds to them. Useful for adding scopes like "deps" or "release".
	 */
	additionalScopes?: string[];

	/**
	 * Release commit format.
	 *
	 * @remarks
	 * - `"semver"`: `release: v1.2.3`
	 * - `"packages"`: `release: version packages`
	 * - `"scoped"`: `release(pkg): v1.2.3`
	 *
	 * @defaultValue Auto-detected from versioning strategy
	 */
	releaseFormat?: ReleaseFormat;

	/**
	 * Enable emojis in prompt configuration.
	 *
	 * @defaultValue false
	 */
	emojis?: boolean;

	/**
	 * Maximum body line length.
	 *
	 * @remarks
	 * Set higher than the conventional 100 to accommodate detailed
	 * commit messages, especially those generated by AI tools.
	 *
	 * @defaultValue 300
	 */
	bodyMaxLineLength?: number;

	/**
	 * Reject markdown formatting in commit messages.
	 *
	 * @remarks
	 * When enabled, commit messages containing markdown formatting
	 * will be rejected. This includes:
	 * - Headers (`#`, `##`, etc.)
	 * - Bullet lists (`-`, `*`)
	 * - Numbered lists (`1.`, `2.`)
	 * - Code fences (triple backticks)
	 * - Links (`[text](url)`)
	 * - Bold/italic formatting
	 *
	 * This helps ensure commit messages are plain text and readable
	 * in terminals and tools that don't render markdown. Particularly
	 * useful for preventing overly-formatted AI-generated commits.
	 *
	 * @defaultValue true
	 */
	noMarkdown?: boolean;

	/**
	 * Working directory for auto-detection.
	 *
	 * @remarks
	 * Used as the starting point for detecting DCO files, workspace
	 * packages, and versioning strategy.
	 *
	 * @defaultValue process.cwd()
	 */
	cwd?: string;
}

/**
 * Resolved configuration options after Zod parsing applies defaults.
 *
 * @remarks
 * This type represents the options after schema validation, where
 * all defaulted fields are guaranteed to have values.
 *
 * @internal
 */
export type ResolvedConfigOptions = z.output<typeof ConfigOptionsSchema>;
