/**
 * Commitlint rule definitions and constants.
 *
 * @internal
 */
import type { CommitTypeDefinition } from "./types.js";

/**
 * Allowed commit types for conventional commits.
 *
 * @remarks
 * Extends the standard conventional commit types with:
 * - `ai`: For AI/LLM agent document updates (CLAUDE.md, context files)
 * - `release`: For release commits (version bumps, changelogs)
 *
 * Types are sorted alphabetically for consistent ordering.
 *
 * @public
 */
export const COMMIT_TYPES = [
	"ai",
	"build",
	"chore",
	"ci",
	"docs",
	"feat",
	"fix",
	"perf",
	"refactor",
	"release",
	"revert",
	"style",
	"test",
] as const;

/**
 * Union type of all valid commit types.
 *
 * @public
 */
export type CommitType = (typeof COMMIT_TYPES)[number];

/**
 * Commit type definitions with metadata for prompts and changelogs.
 *
 * @remarks
 * Each definition provides human-readable text for interactive commit
 * tools and changelog generation. The order here determines display
 * order in prompts (most common types first).
 *
 * @public
 */
export const COMMIT_TYPE_DEFINITIONS: readonly CommitTypeDefinition[] = [
	{
		type: "ai",
		description: "AI/LLM agent document updates (CLAUDE.md, context files)",
		title: "AI Context",
	},
	{
		type: "feat",
		description: "A new feature",
		title: "Features",
	},
	{
		type: "fix",
		description: "A bug fix",
		title: "Bug Fixes",
	},
	{
		type: "docs",
		description: "Documentation only changes",
		title: "Documentation",
	},
	{
		type: "style",
		description: "Code style changes (formatting, semicolons, etc)",
		title: "Styles",
	},
	{
		type: "refactor",
		description: "Code change that neither fixes a bug nor adds a feature",
		title: "Code Refactoring",
	},
	{
		type: "perf",
		description: "A code change that improves performance",
		title: "Performance Improvements",
	},
	{
		type: "test",
		description: "Adding missing tests or correcting existing tests",
		title: "Tests",
	},
	{
		type: "build",
		description: "Changes to build system or external dependencies",
		title: "Builds",
	},
	{
		type: "ci",
		description: "Changes to CI configuration files and scripts",
		title: "Continuous Integration",
	},
	{
		type: "chore",
		description: "Other changes that don't modify src or test files",
		title: "Chores",
	},
	{
		type: "revert",
		description: "Reverts a previous commit",
		title: "Reverts",
	},
	{
		type: "release",
		description: "Release commits (version bumps, changelogs)",
		title: "Releases",
	},
] as const;

/**
 * Default maximum line length for commit body.
 *
 * @remarks
 * Set to 300 characters to accommodate detailed commit messages,
 * especially those generated by AI tools which tend to be more verbose.
 *
 * @public
 */
export const DEFAULT_BODY_MAX_LINE_LENGTH = 300;

/**
 * DCO (Developer Certificate of Origin) signoff text.
 *
 * @remarks
 * This is the standard DCO signoff prefix. When DCO is required,
 * commit messages must include a trailer in the format:
 * `Signed-off-by: Name <email>`
 *
 * @public
 */
export const DCO_SIGNOFF_TEXT = "Signed-off-by:";
